# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: GCS-Py
#email:
description: >- # this means to ignore newlines until "baseurl:"
  All things py that is relevant to the AQA Computer Science GCSE course.
baseurl: "/gcs-py/" # the subpath of your site, e.g. /blog
url: "https://ldproj.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  ldproj

# Build settings
#theme: minima
remote_theme: pmarsceill/just-the-docs
#theme: just-the-docs
plugins:
  - jemoji
  - jekyll-redirect-from
  # - jekyll-feed
  # - jekyll-seo-tag
  # - jekyll-sitemap
  # - jekyll-avatar
  # - jekyll-mentions
  # - jekyll-include-cache
whitelist:
  - jekyll-redirect-from

exclude: ["*.bak", "node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE", "lib/", "bin/", "README.md", "Rakefile"]

permalink: pretty

# defaults:
#   - scope:
#       path: docs/exercises/sections
#       # type: pages
#       # title: Page
#     values:
#       # layout: default
#       # parent: Exercises
#       permalink: "sections/:title:output_ext"
# Enable or disable the site search
search_enabled: true

# Heading anchor links appear on hover over h1-h6 tags
# in page content allowing users to deep link to a particular
# heading on a page.
#
# Supports true (default) or false/nil
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "GCS-Py on GitHub":
    - "//github.com/ldproj/gcs-py"

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2019 ldproj. Distributed by an <a href=\"https://github.com/ldproj/gcs-py/blob/master/LICENSE\">GNU General Public License v3.0.</a>"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
#ga_tracking: UA-2709176-10

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blank_lines: false
  profile: false